### ISSUE TITLE
zero length unicode string causes assertion failure

### ISSUE THREAD

**Issue by bkmartinjr** [TileDB-Inc/TileDB-Py#290]
tiledb version 0.5.6

attempting to write zero-length unicode array triggers assertion

test case:
```
attrs = [tiledb.Attr(name="foo", dtype=np.unicode)]
domain = tiledb.Domain(tiledb.Dim(domain=(0, 1000), tile=1000))
schema = tiledb.ArraySchema(domain=domain, sparse=False, attrs=attrs)
tiledb.DenseArray.create("foo", schema)

with tiledb.DenseArray("foo", mode="w") as A:
    # change empty string to non-empty and things work
    val = np.array(['' for i in range(0, 1001)], dtype=np.unicode)
    A[:] = val
```

result:
```
# python foo.py
Traceback (most recent call last):
  File "foo.py", line 61, in <module>
    A[:] = np.zeros((1000,), dtype=np.unicode)
  File "tiledb/libtiledb.pyx", line 4175, in tiledb.libtiledb.DenseArrayImpl.__setitem__
  File "tiledb/libtiledb.pyx", line 274, in tiledb.libtiledb._write_array
  File "tiledb/np2buf.pyx", line 108, in tiledb.libtiledb.array_to_buffer
AssertionError
```

**Comment by bkmartinjr** [comment]
@ihnorton - any thoughts on a possible work-around for this (short of adding a value to each item)?

**Comment by ihnorton** [comment]
Hi @bkmartinjr, I don't have a work-around, but I will have a fix merged soon, along with updated wheels (these are pending anyway to update for the TileDB core [release](https://github.com/TileDB-Inc/TileDB/releases/tag/1.7.6) a few days ago -- some small changes and a backport).

**Comment by bkmartinjr** [comment]
Super cool - that is even better.  As always, thanks for your rapid response.

**Comment by ihnorton** [comment]
Thanks for the bug report. Fixed by #291, wheels are up [on pypi](https://pypi.org/project/tiledb/0.5.7/).

**Comment by bkmartinjr** [comment]
@ihnorton - I am still getting the same assertion after upgrading to latest release.   Using 0.5.7.  Test case above still fails in the same way:

Traceback (most recent call last):
  File "foo.py", line 62, in <module>
    A[:] = val
  File "tiledb/libtiledb.pyx", line 4175, in tiledb.libtiledb.DenseArrayImpl.__setitem__
  File "tiledb/libtiledb.pyx", line 274, in tiledb.libtiledb._write_array
  File "tiledb/np2buf.pyx", line 108, in tiledb.libtiledb.array_to_buffer
AssertionError

I have double-checked that I'm using 0.5.7...

**Comment by ihnorton** [comment]
Hi @bkmartinjr, I can repro, investigating.

**Comment by ihnorton** [comment]
Ok, the linux wheels did not build the correct version of the code. I will do another release immediately with corrected wheels (need to bump version because PyPI is immutable). Confirmed that mac wheels work fine in a clean build.

My apologies for this, I tested the wheels with your code before uploading, but my test environment on linux also had a local build, which was preferred, so I didn't catch the problem.

**Comment by bkmartinjr** [comment]
No worries!  Thanks for the turn-around.

**Comment by ihnorton** [comment]
Ok, TileDB-Py 0.5.8 wheels are up. Tested cleanly on linux and mac. Will leave open until you have a chance to confirm.

**Comment by bkmartinjr** [comment]
Confirmed as working!   Thank you....
